apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    component: postgres
spec:
  type: LoadBalancer
  selector:
    component: postgres
  ports:
  - name: "postgres"
    port: 5432
    protocol: TCP
status:
  loadBalancer: {}
