name: Close Issues
on:
  release:
    types: [published]
permissions:
  contents: read

jobs:
  close_issues:
    name: Close issues mentioned in pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Close PR Issues
        uses: botpress/gh-actions/close_pull_request_issues@v2
        with:
          comment: Available on ${{ github.event.release.tag_name }}
