name: Codestyle
on: [push]
jobs:
  run_prettier:
    name: Run Prettier on codebase
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        npm install prettier@`node -p -e "require('./package.json').devDependencies.prettier"`
    - name: Run Prettier
      run: |
        ./node_modules/prettier/bin-prettier.js --version
        ./node_modules/prettier/bin-prettier.js --check '{src,modules}/**/*.ts' '!**/*.d.ts'
