name: Codestyle
on: [pull_request]
jobs:
  run_prettier:
    name: Run Prettier on codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          yarn
      - name: Run Prettier
        run: |
          ./node_modules/prettier/bin-prettier.js --check '{src,modules}/**/*.ts' '!**/*.d.ts'
  tslint:
    name: Run TSLint on codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          yarn
      - name: Run TSLint
        run: |
          yarn run tslint
      - name: Get changed files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run TSLint (new rules)
        run: |
          yarn run tslint -c tslint.newrules.json ${{ steps.get_file_changes.outputs.all}}
