name: Pre-Release
on:
  push:
    branches:
      - master
jobs:
  release_bin:
    name: Create Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Get Release Details
        id: release_details
        uses: botpress/gh-actions/get_release_details@next

      - name: Display Release Details
        id: changelog
        run: |
          echo "Changelog: ${{ steps.release_details.outputs.changelog }}"
          echo "Is new release?: ${{ steps.release_details.outputs.is_new_release }}"
          echo "Version: ${{ steps.release_details.outputs.version }}"
          echo "Latest Tag: ${{ steps.release_details.outputs.latest_tag }}"

      - name: Release
        if: ${{ steps.release_details.outputs.is_new_release == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          draft: false
          body: ${{ steps.release_details.outputs.changelog }}
          name: v${{ steps.release_details.outputs.version }}
          tag_name: v${{ steps.release_details.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
