name: Deploy Integrations Staging

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      force:
        description: 'Force re-deploying integrations'
        type: boolean
        required: false
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Deploy Integrations
        uses: ./.github/actions/deploy-integrations
        with:
          environment: 'staging'
          force: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force == 'true' }}
          sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          token_cloud_ops_account: ${{ secrets.STAGING_TOKEN_CLOUD_OPS_ACCOUNT }}
          cloud_ops_workspace_id: ${{ secrets.STAGING_CLOUD_OPS_WORKSPACE_ID }}
          gmail_secrets: '' # secrets should already exist
          linear_secrets: '' # secrets should already exst
          slack_secrets: '' # secrets should already exist
          extra_filter: '-F "!asana" -F "!dalle" -F "!discord" -F "!github" -F "!gmail" -F "!googlecalendar" -F "!gsheets" -F "!instagram" -F "!intercom" -F "!line" -F "!linear" -F "!mailchimp" -F "!make" -F "!messenger" -F "!notion" -F "!slack" -F "!stripe" -F "!sunco" -F "!teams" -F "!trello" -F "!twilio" -F "!viber" -F "!vonage" -F "!webchat" -F "!webhook" -F "!whatsapp" -F "!zapier" -F "!zendesk"' # TODO: remove this line; its only a test

